import { describe, it, expect } from 'vitest';
import { fixFor, packageName, type OsvRecord } from './advisory';
import { readCargoLock, readPipfileLock, readPoetryLock, readRequirements, readUvLock, readYarnLock } from './lockfile';
import { mirrorSource } from './mirror';
import { apiSource, type Fetcher } from './osv';
import { runScan } from './scan';
import { reconcile, EMPTY_TRACKING, trackKey } from './tracking';

const versions = (r: { packages: { name: string; version: string }[] }) => r.packages.map((p) => `${p.name}@${p.version}`);
const skippedNames = (r: { skipped: { name: string }[] }) => r.skipped.map((s) => s.name);

describe('yarn.lock', () => {
  it('reads v1: one entry per header, and counts what was not resolved from the registry', () => {
    const v1 = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


"@babel/core@^7.0.0", "@babel/core@^7.29.0":
  version "7.29.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.29.0.tgz#abc"
  integrity sha512-x

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#def"

mylib@file:../mylib:
  version "0.0.1"
`;
    const r = readYarnLock(v1);
    expect(r.ecosystem).toBe('npm');
    expect(versions(r)).toEqual(['@babel/core@7.29.0', 'lodash@4.17.21']);
    expect(skippedNames(r)).toEqual(['mylib']);
  });

  it('reads berry: only npm: resolutions are registry versions', () => {
    const berry = `__metadata:
  version: 8
  cacheKey: 10

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10/abc

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."

"left-pad@patch:left-pad@npm%3A1.3.0#./.patches/x.patch":
  version: 1.3.0
  resolution: "left-pad@patch:left-pad@npm%3A1.3.0#./.patches/x.patch"
`;
    const r = readYarnLock(berry);
    expect(versions(r)).toEqual(['lodash@4.17.21']);
    expect(skippedNames(r).sort()).toEqual(['app', 'left-pad']);
  });

  it('refuses a text that is neither yarn format', () => {
    expect(() => readYarnLock('hello')).toThrow(/NOT_A_LOCKFILE/);
  });
});

describe('Python lockfiles', () => {
  it('reads Pipfile.lock default and develop, pinned versions only', () => {
    const lock = JSON.stringify({
      _meta: {}, default: { django: { version: '==3.2.0' }, mylib: { path: '.' } },
      develop: { pytest: { version: '==7.0.0' }, tool: { git: 'https://x/y.git' } },
    });
    const r = readPipfileLock(lock);
    expect(r.ecosystem).toBe('PyPI');
    expect(versions(r)).toEqual(['django@3.2.0', 'pytest@7.0.0']);
    expect(skippedNames(r)).toEqual(['mylib', 'tool']);
  });

  it('reads poetry.lock and counts packages from git or a path', () => {
    const poetry = `[[package]]
name = "requests"
version = "2.25.0"
description = "HTTP"
optional = false

[[package]]
name = "mytool"
version = "0.1.0"

[package.source]
type = "git"
url = "https://github.com/a/mytool.git"
reference = "main"

[metadata]
lock-version = "2.0"
`;
    const r = readPoetryLock(poetry);
    expect(versions(r)).toEqual(['requests@2.25.0']);
    expect(skippedNames(r)).toEqual(['mytool']);
  });

  it('reads uv.lock: only registry sources are asked', () => {
    const uv = `version = 1

[[package]]
name = "numpy"
version = "1.21.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "myproject"
version = "0.1.0"
source = { editable = "." }
`;
    const r = readUvLock(uv);
    expect(versions(r)).toEqual(['numpy@1.21.0']);
    expect(skippedNames(r)).toEqual(['myproject']);
  });

  it('reads requirements.txt pins, and counts every unpinned or editable line', () => {
    const req = `# comment
Django==3.2.0  # pinned
requests[security]==2.25.0 ; python_version >= "3.8"
numpy>=1.20
flask
-r other.txt
-e git+https://github.com/a/b.git#egg=bee
--hash=sha256:abc
`;
    const r = readRequirements(req);
    expect(versions(r)).toEqual(['Django@3.2.0', 'requests@2.25.0']);
    expect(skippedNames(r).sort()).toEqual(['bee', 'flask', 'numpy']);
  });
});

describe('Cargo.lock', () => {
  it('reads registry crates, counts git ones, and leaves the workspace crates out', () => {
    const cargo = `version = 3

[[package]]
name = "time"
version = "0.1.43"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"

[[package]]
name = "mycrate"
version = "0.1.0"

[[package]]
name = "forked"
version = "1.0.0"
source = "git+https://github.com/a/forked#abc"
`;
    const r = readCargoLock(cargo);
    expect(r.ecosystem).toBe('crates.io');
    expect(versions(r)).toEqual(['time@0.1.43']);
    expect(skippedNames(r)).toEqual(['forked']);
  });
});

describe('fixFor outside SEMVER', () => {
  const django: OsvRecord = {
    id: 'PYSEC-2021-9', modified: 'm',
    affected: [{ package: { ecosystem: 'PyPI', name: 'django' }, ranges: [{ type: 'ECOSYSTEM', events: [
      { introduced: '2.2' }, { fixed: '2.2.18' }, { introduced: '3.0' }, { fixed: '3.0.12' }, { introduced: '3.1' }, { fixed: '3.1.6' },
    ] }] }],
  };

  it('orders plain PyPI releases (the record measured on 2026-10-04) and names the fix of the right interval', () => {
    expect(fixFor(django, 'Django', '3.0.5', 'PyPI')).toEqual({ kind: 'fixed', version: '3.0.12' });
    expect(fixFor(django, 'django', '2.2', 'PyPI')).toEqual({ kind: 'fixed', version: '2.2.18' });
  });

  it('says "stated in the record" for a version it cannot order, never "not stated"', () => {
    expect(fixFor(django, 'django', '3.0.5+cpu', 'PyPI')).toEqual({ kind: 'see' });
    // A pre-release is ordered (PEP 440): it gets its fixed version, not a pointer to the record.
    expect(fixFor(django, 'django', '3.0.5rc1', 'PyPI')).toEqual({ kind: 'fixed', version: '3.0.12' });
  });

  it('compares PyPI names the way PyPI does (PEP 503)', () => {
    expect(packageName('Typing_Extensions', 'PyPI')).toBe(packageName('typing-extensions', 'PyPI'));
    expect(packageName('Typing_Extensions', 'npm')).toBe('Typing_Extensions');
  });
});

describe('one scan, several ecosystems', () => {
  it('asks a Python project online even when npm reads the local database, and says so per ecosystem', async () => {
    const asked: string[] = [];
    const fetcher: Fetcher = async (url, init) => {
      if (url.endsWith('/querybatch')) {
        const { queries } = JSON.parse(String(init?.body)) as { queries: { package: { ecosystem: string } }[] };
        asked.push(...queries.map((q) => q.package.ecosystem));
        return new Response(JSON.stringify({ results: queries.map(() => ({})) }), { status: 200 });
      }
      return new Response('{}', { status: 404 });
    };
    const mirror = mirrorSource({ query: async () => ({ asOf: '2026-10-04T00:00:00Z', records: [] }) });
    const res = await runScan({
      sourceFor: (eco) => (eco === 'npm' ? mirror : apiSource(fetcher)),
      cache: { read: async () => null, write: async () => {} },
      locks: [
        { file: 'pnpm-lock.yaml', read: { kind: 'pnpm', ecosystem: 'npm', packages: [{ ecosystem: 'npm', name: 'tar', version: '7.5.21' }], skipped: [] } },
        { file: 'requirements.txt', read: { kind: 'requirements', ecosystem: 'PyPI', packages: [{ ecosystem: 'PyPI', name: 'django', version: '3.2.0' }], skipped: [] } },
      ],
    });
    expect(asked).toEqual(['PyPI']);
    expect(res.sources).toEqual([
      { ecosystem: 'npm', kind: 'mirror', asOf: '2026-10-04T00:00:00Z' },
      { ecosystem: 'PyPI', kind: 'api', asOf: null },
    ]);
    expect(res.complete).toBe(true);
  });

  it('never answers a package of another ecosystem from a mirror', async () => {
    const mirror = mirrorSource({ query: async () => ({ asOf: 'd', records: [] }) });
    const out = await mirror.hits([{ ecosystem: 'PyPI', name: 'django', version: '3.2.0' }]);
    expect(out.unasked).toHaveLength(1);
    expect(out.error).toBe('MIRROR_OTHER_ECOSYSTEM');
    const py = mirrorSource({ query: async () => ({ asOf: 'd', records: [] }) }, 'PyPI');
    expect((await py.hits([{ ecosystem: 'PyPI', name: 'django', version: '3.2.0' }])).unasked).toHaveLength(0);
  });
});

describe('tracking across ecosystems', () => {
  it('keeps two packages of the same name in two ecosystems apart, and npm keys as they were', () => {
    const t = reconcile(EMPTY_TRACKING, {
      at: 'x', lockfileComplete: true,
      findings: [{ id: 'X-1', ecosystem: 'npm', name: 'six', version: '1.0.0' }, { id: 'X-1', ecosystem: 'PyPI', name: 'six', version: '1.0.0' }],
      installed: [{ ecosystem: 'npm', name: 'six', version: '1.0.0', asked: true }, { ecosystem: 'PyPI', name: 'six', version: '1.0.0', asked: true }],
    });
    expect(t.entries).toHaveLength(2);
    expect(t.entries.find((e) => !e.ecosystem)).toBeTruthy();
    expect(trackKey('X-1', 'six')).toBe('X-1|six');
    expect(trackKey('X-1', 'six', 'PyPI')).toBe('X-1|PyPI:six');
  });

  it('does not call a Python package removed when only the npm lockfile is installed', () => {
    const before = reconcile(EMPTY_TRACKING, {
      at: 'x', lockfileComplete: true,
      findings: [{ id: 'P-1', ecosystem: 'PyPI', name: 'django', version: '3.2.0' }],
      installed: [{ ecosystem: 'PyPI', name: 'django', version: '3.2.0', asked: true }],
    });
    // The same project, scanned while its requirements.txt could not be read.
    const after = reconcile(before, { at: 'y', findings: [], installed: [], lockfileComplete: false });
    expect(after.entries[0]!.state).toBe('open');
  });
});

describe('tracking a PyPI package across lockfile spellings', () => {
  it('keeps the same entry when the lockfile changes the spelling of a name', () => {
    const before = reconcile(EMPTY_TRACKING, {
      at: 'x', lockfileComplete: true,
      findings: [{ id: 'P-1', ecosystem: 'PyPI', name: 'Django', version: '3.2.0' }],
      installed: [{ ecosystem: 'PyPI', name: 'Django', version: '3.2.0', asked: true }],
    });
    const after = reconcile(before, {
      at: 'y', lockfileComplete: true,
      findings: [{ id: 'P-1', ecosystem: 'PyPI', name: 'django', version: '3.2.0' }],
      installed: [{ ecosystem: 'PyPI', name: 'django', version: '3.2.0', asked: true }],
    });
    expect(after.entries).toHaveLength(1);
    expect(after.entries[0]).toMatchObject({ state: 'open', since: 'x' });
  });
});
